Public Class DPMTRLINE
    Public Property COMPANY As Short
    Public Property FINDOC As Integer
    Public Property MTRLINES As Integer
    Public Property LINENUM As Integer
    Public Property SODTYPE As Short
    Public Property MTRL As Integer
    Public Property PENDING As Short
    Public Property RESTMODE As Short?
    Public Property SOSOURCE As Integer
    Public Property SOREDIR As Integer
    Public Property SCODE As String
    Public Property MTRTYPE As Short
    Public Property SOTYPE As Short
    Public Property WHOUSE As Short?
    Public Property WHOUSESEC As Short?
    Public Property MTRUNIT As Short?
    Public Property VAT As Short
    Public Property PRJC As Integer?
    Public Property PRJLINES As Integer?
    Public Property PRJCSTAGE As Short?
    Public Property MTRPRJCBLD As Short?
    Public Property SOEXPTYPE As Short?
    Public Property SALESMAN As Integer?
    Public Property RSRC As Integer?
    Public Property MTRLOT As Integer?
    Public Property ASSDEPR As Integer?
    Public Property WHOUSEBIN As Short?
    Public Property WHOUSEBINSEC As Short?
    Public Property BUSUNITS As Short?
    Public Property MTRSEASON As Short?
    Public Property MTRCATEGORY As Short?
    Public Property PRCPOLICY As Short?
    Public Property SPCS As Integer?
    Public Property MTRPACK As Integer?
    Public Property QTYP As Double?
    Public Property QTY As Double?
    Public Property QTY1 As Double
    Public Property QTY2 As Double
    Public Property QTY1COV As Double
    Public Property QTY1CANC As Double
    Public Property QTY1FCOV As Double
    Public Property SHIPDATE As Date?
    Public Property DELIVDATE As Date?
    Public Property WEIGHT As Double?
    Public Property VOLUME As Double?
    Public Property INTVAL As Double?
    Public Property INTVAT As Double?
    Public Property BGINTCOUNTRY As Short?
    Public Property BGINTDISTRICT As Short?
    Public Property DUTY As Double?
    Public Property PLSMVAL As Double?
    Public Property PLSMVAT As Double?
    Public Property PRICE As Double?
    Public Property PRICE1 As Double?
    Public Property LINEVAL As Double?
    Public Property LLINEVAL As Double?
    Public Property EXPVAL As Double?
    Public Property LEXPVAL As Double
    Public Property LEXPVAL1 As Double?
    Public Property LEXPVATVAL1 As Double?
    Public Property DISC1PRC As Double?
    Public Property DISC2PRC As Double?
    Public Property DISC3PRC As Double?
    Public Property DISC1VAL As Double?
    Public Property LDISC1VAL As Double?
    Public Property DISC2VAL As Double?
    Public Property LDISC2VAL As Double?
    Public Property DISC3VAL As Double?
    Public Property LDISC3VAL As Double?
    Public Property NETLINEVAL As Double
    Public Property LNETLINEVAL As Double
    Public Property VATAMNT As Double
    Public Property LVATAMNT As Double
    Public Property LVATNOEXM As Double?
    Public Property SALESCVAL As Double?
    Public Property EFKVAL As Double
    Public Property COMMENTS As String
    Public Property COMMENTS1 As String
    Public Property COMMENTS2 As String
    Public Property DIMENSION1 As Double?
    Public Property DIMENSION2 As Double?
    Public Property DIMENSION3 As Double?
    Public Property TRNLINEVAL As Double?
    Public Property LTRNLINEVAL As Double?
    Public Property PRCRULEDATA As String
    Public Property INSTALMENTS As Short?
    Public Property WASTE As Double?
    Public Property COSTCOEF As Double?
    Public Property CONVPRC As Double?
    Public Property STAGE As Short?
    Public Property STAGELINENUM As Short?
    Public Property ACNMSK As String
    Public Property ACNMSK1 As String
    Public Property FINDOCS As Integer?
    Public Property MTRLINESS As Integer?
    Public Property FINDOCL As Integer?
    Public Property MTRLINESL As Integer?
    Public Property SOANAL As String
    Public Property SXMSKK As Integer?
    Public Property SXPERC As Double?
    Public Property BGLEXCISE As Double?
    Public Property AUTOPRDDOC As Short
    Public Property ACNMSKS As String
    Public Property ACNMSKX As String
    Public Property COSTCNTR As Integer?
    Public Property ITECALCTYPE As Short?
    Public Property GUARTIME As Short?
    Public Property SRVDEBITTYPE As Short?
    Public Property PACKSTATUS As Short?
    Public Property PACKCODE1 As String
    Public Property PACKCODE2 As String
    Public Property LWMARKUP As Double?
    Public Property LRMARKUP As Double?
    Public Property NUM01 As Double?
    Public Property NUM02 As Double?
    Public Property NUM03 As Double?
    Public Property NUM04 As Double?
    Public Property BOOL01 As Short?
    Public Property BOOL02 As Short?
    Public Property DATE01 As Date?
    Public Property DATE02 As Date?
    Public Property UFTBL01 As Short?
    Public Property UFTBL02 As Short?
    Public Property cccTrdDep As Integer?
    Public Property cccTrdr As Integer?
    Public Property INST As Integer?
    Public Property CNTR As Integer?
    Public Property VAT1 As Integer?
    Public Property CUSTOMSLOT As Integer?
    Public Property CMTRUNIT As Short?
    Public Property QUANTITY As Double?
    Public Property GROSSMASS As Double?
    Public Property NETMASS As Double?
    Public Property BOND As Integer?
    Public Property PSPCS As Integer?
    Public Property ACNDOCCATEGORY As Integer?
    Public Property MYDATACODE As Short?
    Public Property ACNMODEL As Short?
    Public Property CPVCODE As Integer?
    Public Property ccCAFINDOC As Integer?
    Public Property ccCAMTRLINES As Integer?
    Public Property INTEXP As Double?
    Public Property LINETAXVAL As Double?
    Public Property LLINETAXVAL As Double?
    Public Property cccAGFindoc As Integer?
    Public Property cccAGMtrlines As Integer?
    Public Property cccAGMtrl As Integer?
    Public Property CccDocs As String
End Class
