DECLARE @MTRL AS INTEGER = 2115 --63 --NULL --384 --NULL
DECLARE @CODE AS varchar(25) = '2103030557'--'%305%'
DECLARE @COMPANY AS INTEGER = 1000
DECLARE @SODTYPE AS INTEGER = 51
DECLARE @WHOUSE  AS VARCHAR(250) = '2|4'
--DECLARE @MTRLS  AS VARCHAR(250) = ''

DECLARE @DFROM AS datetime = '20170701'
DECLARE @DTO AS datetime = '20170801'
DECLARE @FISCPRD AS INTEGER = 2017
DECLARE @PERIOD AS INTEGER = 7


	--Εγκατάσταση (Σύντμηση)	Ονομασία Εγκατάστασης	Κωδικός Υλικού	Περιγραφή Υλικού	Μονάδα Μέτρησης	Ποσότητα Αποθέματος
		SELECT        WHOUSE.SHORTCUT, WHOUSE.NAME AS WHNAME, MTRL.CODE, MTRL.NAME, MTRUNIT.NAME, SUM(U.BAL) AS TBAL
		FROM            (SELECT        COMPANY, WHOUSE, MTRL, FISCPRD, SUM(ISNULL(IMPQTY1, 0) - ISNULL(EXPQTY1, 0)) AS BAL
								  FROM            MTRBALSHEET AS MB
								  WHERE        (PERIOD < @PERIOD)
								  GROUP BY MTRL, WHOUSE, COMPANY, FISCPRD
								  UNION ALL
								  SELECT        T.COMPANY, T.WHOUSE, T.MTRL, T.FISCPRD, SUM(TP.FLG01 * ISNULL(T.QTY1, 0) - TP.FLG04 * ISNULL(T.QTY1, 0)) AS BAL
								  FROM            MTRTRN AS T INNER JOIN
														   TPRMS AS TP ON TP.COMPANY = T.COMPANY AND TP.SODTYPE = T.SODTYPE AND TP.TPRMS = T.TPRMS
								  WHERE        (T.SODTYPE = @SODTYPE) AND (T.TRNDATE >= @DFROM) AND (T.TRNDATE < @DTO)
								  GROUP BY T.MTRL, T.WHOUSE, T.COMPANY, T.FISCPRD) AS U INNER JOIN
                         MTRL ON U.MTRL = MTRL.MTRL INNER JOIN
                         WHOUSE ON U.COMPANY = WHOUSE.COMPANY AND U.WHOUSE = WHOUSE.WHOUSE INNER JOIN
                         MTRUNIT ON MTRL.COMPANY = MTRUNIT.COMPANY AND MTRL.MTRUNIT1 = MTRUNIT.MTRUNIT
		WHERE        (U.COMPANY = @COMPANY) AND (U.FISCPRD = @FISCPRD) AND (U.WHOUSE IN (SELECT item from fnSplit(@WHOUSE, '|'))) AND (CODE LIKE @CODE)
		GROUP BY MTRL.CODE, MTRL.NAME, WHOUSE.SHORTCUT, WHOUSE.NAME, MTRUNIT.NAME
		ORDER BY WHOUSE.SHORTCUT
